#!/usr/bin/env bash
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20G
#SBATCH --job-name=step2_map
#SBATCH --partition=standard
#SBATCH --output=_logs/step2_%A_%a.log

# =============================================================================
# 2_01_step2_map.sh
#
# SLURM array wrapper for scifi-demux step2 per-well mapping + cleaning.
# Each array task maps one (well, genome) pair through the full pipeline:
#   BWA mem -> sort -> BC tagging + MAPQ >= 10 filter -> Picard dedup -> fixBC -> Tn5 BED
#
# Uses the scifi-demux step2 CLI in HPC mode:
#   - $SLURM_ARRAY_TASK_ID selects one row from the run_plan TSV
#   - --from-step1-work-root discovers the FASTQs (phase 2 merged layout of 01_preprocessing)
#   - --resume skips tasks with existing sentinels (safe to re-submit)
#
# Usage (from ${PROJECT_ROOT}/3_Mapping; PLANS = <repo>/workflows/02_mapping/zhang2024):
#   sbatch --array=1-192  2_01_step2_map.sh ${PLANS}/run_plan.B73Mo17_rep1.tsv        B73Mo17_rep1
#   sbatch --array=1-192  2_01_step2_map.sh ${PLANS}/run_plan.B73Mo17_rep2.tsv        B73Mo17_rep2
#   sbatch --array=1-672  2_01_step2_map.sh ${PLANS}/run_plan.multiGenotypes_rep1.tsv multiGenotypes_rep1
#
# Input:  run_plan TSV (one row per well x genome, generated by 0_generate_run_plans.sh)
# Output: 3_Mapping/{DATASET_REP}/{WELL}/{WELL}_{GENOME}_scifiATAC.mq10.BC.rmdup.mm.bam
# =============================================================================

set -euo pipefail
: "${PROJECT_ROOT:?set PROJECT_ROOT to the analysis tree that holds 2_CleanReads/ and 3_Mapping/}"

########## Environment #########
# conda activate <env from environment.yml>
module load Bioinformatics bwa/0.7.17-mil4ns7   # HPC module for BWA 0.7.17; adapt to the local installation

########## Arguments #########
RUN_PLAN="${1:?Usage: sbatch --array=1-N 2_01_step2_map.sh <RUN_PLAN_TSV> <DATASET_REP>}"
DATASET_REP="${2:?Missing DATASET_REP argument}"

########## Paths #########
BASEDIR="${PROJECT_ROOT}"
MAPPING_DIR="${BASEDIR}/3_Mapping"
FASTQ_DIR="${BASEDIR}/2_CleanReads/combined/${DATASET_REP}"
OUTDIR="${MAPPING_DIR}/${DATASET_REP}"

cd "${MAPPING_DIR}"
mkdir -p _logs

########## Run step2 via CLI #########
echo "[$(date)] Task ${SLURM_ARRAY_TASK_ID}: dataset=${DATASET_REP} plan=${RUN_PLAN}"

scifi-demux step2 run \
  --mode hpc \
  --plan "${RUN_PLAN}" \
  --sample "${DATASET_REP}" \
  --from-step1-work-root "${FASTQ_DIR}" \
  --outdir "${OUTDIR}" \
  --mapq-min 10 \
  --no-dry-run

echo "[$(date)] Done: task ${SLURM_ARRAY_TASK_ID}"
